name: Bunkercore CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install
        run: npm install
      - name: Check Syntax
        run: node -e "console.log('Build OK')"
