name: >-
  organizations/452327875557/constraints/iam.managed.workloadIdentityPoolAwsAccounts
resource_types: iam.googleapis.com/WorkloadIdentityPoolProvider
method_types:
  - CREATE
  - UPDATE
condition: resource.aws.accountId in parameters.allowedAwsAccountIds
action_type: ALLOW
display_name: >-
  Allowed AWS accounts that can be configured for workload identity federation
  in Cloud IAM
description: >-
  List of AWS account IDs that can be configured for workload identity
  federation in Cloud IAM.
parameters:
  - key: allowedAwsAccountIds
    value:
      type: LIST
      defaultValue: []
      metadata:
        description: The list of allowed AWS account IDs.
